{{- range $env := .Values.environments }}
{{- range $app := $.Values.applications }}

{{- /* Exclusion Logic: Checks if the current environment is in the blocklist */ -}}
{{- $excludedEnvs := default list $app.exclude -}}
{{- if not (has $env.name $excludedEnvs) }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.name }}-{{ $env.name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ $.Values.spec.source.repoURL }}
    path: {{ $app.path }}
    targetRevision: {{ $.Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - values.yaml
        - values-{{ $env.name }}.yaml
  destination:
    server: {{ $.Values.spec.destination.server }}
    namespace: {{ $env.name }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
{{- end }}
{{- end }}