{{- $currentEnv := .Values.environment }}
{{- range $app := .Values.applications }}

{{- /* Exclusion logic */ -}}
{{- $excludedEnvs := default list $app.exclude -}}
{{- if not (has $currentEnv $excludedEnvs) }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.name }}-{{ $currentEnv }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ $.Values.spec.source.repoURL }}
    path: {{ $app.path }}
    targetRevision: {{ $.Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - values.yaml
        - values-{{ $currentEnv }}.yaml
  destination:
    server: {{ $.Values.spec.destination.server }}
    namespace: {{ $currentEnv }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
{{- end }}