apiVersion: v2
name: backend-api
description: Backend API Example
type: application
version: 1.0.0
appVersion: "1.25.0"
dependencies:
  - name: common-library
    version: 1.0.0
    repository: file://../../library/common