spec:
  source:
    repoURL: https://github.com/luans/kubernetes.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc

applications:
  - name: platform-networking
    path: helm-charts/app-of-apps-example/platform/networking
    namespace: istio-ingress

  - name: platform-security
    path: helm-charts/app-of-apps-example/platform/security-policies
    namespace: istio-ingress