spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/luans/kubernetes.git
    targetRevision: HEAD

environments: dev

applications:
  - name: backend-api
    path: helm-charts/app-of-apps-example/charts/backend
    exclude:
      - prod
      - uat

  - name: keycloak
    path: helm-charts/app-of-apps-example/charts/keycloak
    exclude:
      - prod
      - uat