spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/luans/kubernetes.git
    targetRevision: HEAD
    #path: helm-charts/app-of-apps-example/app-of-apps

environments: dev

applications:
  - name: backend-api
    path: helm-charts/app-of-apps-example/charts/backend
    exclude:
      - prod
      - uat

  #- name: frontend-ui
  #  path: charts/frontend
  #  exclude:
  #    - prod
#
  #- name: debug-tools
  #  path: charts/debug-tools
  #  exclude:
  #    - uat
  #    - prod