apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-api
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
  - name: main-gateway
    namespace: istio-ingress
  hostnames:
  - "demo.modernatec.com.br"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: backend-api
      port: 80

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: require-admin-role
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: main-gateway
  action: DENY
  rules:
    - from:
      - source:
          notRequestPrincipals: ["*"]
#  action: ALLOW
#  rules:
#  - to:
#    - operation:
#        paths: ["/health"]
#        methods: ["GET"]
#
#  - from:
#    - source:
#        requestPrincipals: ["*"]
#    to:
#    - operation:
#        paths: ["/*"]
#        methods: ["GET", "POST", "PUT", "DELETE"]