apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-api
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
  - name: main-gateway
    namespace: istio-ingress
  hostnames:
  - "demo.modernatec.com.br"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: backend-api
      port: 80

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: require-admin-role
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      istio: main-gateway
  action: ALLOW
  rules:
  #- to:
  #  - operation:
  #      paths: ["/*"]
  #      methods: ["GET", "POST", "PUT", "DELETE"]

  - from:
    - source:
        requestPrincipals: ["*"]
    when:
    - key: request.auth.claims[groups]
      values: ["admin"]
    to:
    - operation:
        paths: ["/admin/*"]
        methods: ["GET", "POST", "PUT", "DELETE"]